version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_SECRET=change-me
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
    restart: unless-stopped
